# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 13:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cloud/uploads/%Y%m%d')),
                ('date', models.DateField(default=datetime.date.today)),
                ('password', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
